# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirSeatApp', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('location', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'airport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('depart_time', models.DateField()),
                ('arrive_time', models.DateField()),
                ('economy_price', models.FloatField()),
                ('business_price', models.FloatField()),
            ],
            options={
                'db_table': 'flight_schedule',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
